DisableStartupLog: true
DisableInterruptHandler: false
DisablePathCorrection: false
EnablePathEscape: false
EnableEasyJSON: false
EnableOptimizations: false
FireMethodNotAllowed: false
DisableBodyConsumptionOnUnmarshal: false
DisableAutoFireStatusCode: false
TimeFormat: yyyy-MM-dd hh:mm:ss
Charset: UTF-8